-- Phase 2: Knowledge Base / Document / Document Chunk tables for H2 test environment
-- These tables are normally created by V2__knowledge_document_ingestion.sql (Flyway),
-- but in test profile we use H2 with Flyway disabled.

CREATE TABLE IF NOT EXISTS knowledge_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    chunk_strategy VARCHAR(32) NOT NULL DEFAULT 'RECURSIVE',
    chunk_size INTEGER NOT NULL DEFAULT 1000,
    chunk_overlap INTEGER NOT NULL DEFAULT 150,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_knowledge_base PRIMARY KEY (id),
    CONSTRAINT fk_kb_workspace FOREIGN KEY (workspace_id) REFERENCES workspace(id) ON DELETE RESTRICT,
    CONSTRAINT fk_kb_created_by FOREIGN KEY (created_by) REFERENCES sys_user(id) ON DELETE RESTRICT,
    CONSTRAINT chk_kb_status CHECK (status IN ('ACTIVE', 'DELETING'))
);

CREATE INDEX IF NOT EXISTS idx_kb_workspace_created ON knowledge_base (workspace_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_kb_workspace_status ON knowledge_base (workspace_id, status);

CREATE TABLE IF NOT EXISTS document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    knowledge_base_id BIGINT NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    file_extension VARCHAR(16) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    checksum_sha256 CHAR(64) NOT NULL,
    bucket_name VARCHAR(63) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    status VARCHAR(24) NOT NULL,
    chunk_strategy VARCHAR(32) NOT NULL,
    chunk_size INTEGER NOT NULL,
    chunk_overlap INTEGER NOT NULL,
    parser_metadata TEXT NOT NULL DEFAULT '{}',
    failure_code VARCHAR(64),
    failure_message VARCHAR(512),
    cleanup_reason VARCHAR(32),
    cleanup_eligible_at TIMESTAMP,
    created_by BIGINT NOT NULL,
    completed_at TIMESTAMP,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_document PRIMARY KEY (id),
    CONSTRAINT fk_document_kb FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_base(id) ON DELETE RESTRICT,
    CONSTRAINT fk_document_created_by FOREIGN KEY (created_by) REFERENCES sys_user(id) ON DELETE RESTRICT,
    CONSTRAINT uk_document_object_key UNIQUE (object_key)
);

CREATE INDEX IF NOT EXISTS idx_document_kb_created ON document (knowledge_base_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_document_kb_status ON document (knowledge_base_id, status);

CREATE TABLE IF NOT EXISTS document_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    knowledge_base_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    character_count INTEGER NOT NULL,
    token_count INTEGER,
    page_start INTEGER,
    page_end INTEGER,
    section_path VARCHAR(1024),
    start_offset INTEGER,
    end_offset INTEGER,
    source_metadata TEXT,
    embedding TEXT,
    embedding_model VARCHAR(128),
    embedding_generation INTEGER,
    embedding_fence_token BIGINT,
    embedded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_document_chunk PRIMARY KEY (id),
    CONSTRAINT fk_chunk_document FOREIGN KEY (document_id) REFERENCES document(id) ON DELETE CASCADE,
    CONSTRAINT fk_chunk_kb FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_base(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_chunk_document ON document_chunk (document_id, chunk_index);
CREATE INDEX IF NOT EXISTS idx_chunk_kb ON document_chunk (knowledge_base_id);