-- Phase 4: Conversation & Chat Message tables for H2 test environment
-- These tables are normally created by V4__chat_conversation.sql (Flyway),
-- but in test profile we use H2 with Flyway disabled.

CREATE TABLE IF NOT EXISTS conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    title VARCHAR(256) NOT NULL DEFAULT 'New Conversation',
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_conversation PRIMARY KEY (id),
    CONSTRAINT fk_conversation_workspace FOREIGN KEY (workspace_id) REFERENCES workspace(id) ON DELETE CASCADE,
    CONSTRAINT fk_conversation_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE,
    CONSTRAINT chk_conversation_status CHECK (status IN ('ACTIVE', 'ARCHIVED', 'DELETED'))
);

CREATE INDEX IF NOT EXISTS idx_conversation_workspace_user ON conversation (workspace_id, user_id, status, updated_at);
CREATE INDEX IF NOT EXISTS idx_conversation_workspace ON conversation (workspace_id, status);

CREATE TABLE IF NOT EXISTS chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    conversation_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'SUCCESS',
    model VARCHAR(128),
    error_code VARCHAR(64),
    error_message VARCHAR(512),
    citation TEXT,
    token_usage TEXT,
    sequence_no INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_chat_message PRIMARY KEY (id),
    CONSTRAINT fk_chat_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversation(id) ON DELETE CASCADE,
    CONSTRAINT chk_chat_message_role CHECK (role IN ('SYSTEM', 'USER', 'ASSISTANT', 'TOOL')),
    CONSTRAINT chk_chat_message_status CHECK (status IN ('GENERATING', 'SUCCESS', 'FAILED', 'CANCELLED')),
    CONSTRAINT uk_chat_message_conversation_seq UNIQUE (conversation_id, sequence_no)
);

CREATE INDEX IF NOT EXISTS idx_chat_message_conversation_seq ON chat_message (conversation_id, sequence_no);
CREATE INDEX IF NOT EXISTS idx_chat_message_status ON chat_message (status, created_at);