-- Phase 6: API Key table for H2 test environment
-- This table is normally created by V5__api_key.sql (Flyway),
-- but in test profile we use H2 with Flyway disabled.

CREATE TABLE IF NOT EXISTS api_key (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workspace_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    key_prefix VARCHAR(16) NOT NULL,
    key_hash VARCHAR(256) NOT NULL,
    scope VARCHAR(32) NOT NULL DEFAULT 'READ',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    expires_at TIMESTAMP,
    last_used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMP,
    CONSTRAINT pk_api_key PRIMARY KEY (id),
    CONSTRAINT fk_api_key_workspace FOREIGN KEY (workspace_id) REFERENCES workspace(id),
    CONSTRAINT fk_api_key_user FOREIGN KEY (user_id) REFERENCES sys_user(id),
    CONSTRAINT chk_api_key_status CHECK (status IN ('ACTIVE', 'REVOKED')),
    CONSTRAINT uq_api_key_prefix UNIQUE (key_prefix)
);

CREATE INDEX IF NOT EXISTS idx_api_key_prefix ON api_key (key_prefix, status);
CREATE INDEX IF NOT EXISTS idx_api_key_workspace ON api_key (workspace_id, status);
CREATE INDEX IF NOT EXISTS idx_api_key_user ON api_key (user_id, status);